eloitembremande/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from . import views
from .views import ProjetsView, ConcertsView, ContactsView, AmisView

urlpatterns = [
    path('', views.home, name="home"),
    path('projets/', ProjetsView.as_view(extra_context={'title': 'Projets'}), name="projets"),
    path('agenda/', ConcertsView.as_view(extra_context={'title': 'Agenda'}), name="agenda"),
    path('photos/', TemplateView.as_view(template_name="eloitembremande/pages/photos.html", extra_context={'title': 'Photos'}), name="photos"),
    path('amis/', AmisView.as_view(extra_context={'title': 'Amis'}), name="amis"),
    path('contact/', ContactsView.as_view(extra_context={'title': 'Contact'}), name="contact"),
    path('mentions-legales/', TemplateView.as_view(template_name="eloitembremande/pages/mentions-legales.html", extra_context={'title': 'Mentions Légales'}), name="mentions-legales"),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

eloitembremande/models.py
from django.db import models
from tinymce.models import HTMLField

class Projet(models.Model):
    nom = models.CharField(max_length=100, null=False, unique=True)
    instruments = models.CharField(max_length=100, null=True, blank=True, unique=False)
    description = HTMLField()
    telephone = models.CharField(max_length=50, null=True, blank=True)
    mail = models.EmailField(max_length=150, blank=True)
    website = models.URLField(max_length=150, blank=True)
    facebook = models.URLField(max_length=150, blank=True)
    ami = models.BooleanField(help_text="Est-ce un projet ami?", default=False)

    def __str__(self):
        return self.nom

class Concert(models.Model):
    projet = models.ForeignKey('Projet', on_delete=models.SET_NULL, null=True)
    date = models.DateField()
    ville = models.CharField(max_length=50, null=False)
    lieu = models.CharField(max_length=80, blank=True)
    evenement = models.URLField(max_length=150, help_text="Lien vers évènement Facebook", blank=True)

    def __str__(self):
        return self.date.strftime('%d %b %Y')

class Video(models.Model):
    projet = models.ForeignKey('Projet', on_delete=models.CASCADE)
    code = models.CharField(max_length=300, null=False, help_text="code à inscrire pour intégrer la vidéo")

eloitembremande/views.py
from django.views.generic.list import ListView
from .models import Projet, Concert
from django.shortcuts import render

def home(request):
    return render(request, 'eloitembremande/pages/home.html')

class ProjetsView(ListView):
    model = Projet
    template_name = 'eloitembremande/pages/projets.html'

class ConcertsView(ListView):
    model = Concert
    template_name = 'eloitembremande/pages/agenda.html'

class AmisView(ListView):
    model = Projet
    template_name = 'eloitembremande/pages/amis.html'

class ContactsView(ListView):
    model = Projet
    template_name = 'eloitembremande/pages/contact.html'

eloitembremande/templates/eloitembremande/base.html
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html lang="fr-fr">
  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta property="og:title" content="{% if title %}{{ title }}{% else %}Eloi Tembremande{% endif %}">
    <meta property="og:site_name" content="EloiTembremande.com">
    <meta property="og:url" content="https://eloitembremande.com{{ request.path }}">
    <meta property="og:image" content="https://eloitembremande.com/static/img/galeries/galerie1/02.jpg">
    <meta property="og:language" content="fr">
    <title>{% if title %}{{ title }}{% else %}Eloi Tembremande{% endif %}</title>
    <meta name="description" content="{% block description %}Musicien, chef d'orchestre, arrangeur. Bordeaux, France.{% endblock %}">
    {% render_bundle 'app' %}

  </head>
  <body>

    {% block body %}{% endblock %}

    {% block scripts %}{% endblock %}
  </body>
</html>

eloitembremande/templates/eloitembremande/pages/agenda.html
{% extends "eloitembremande/base.html" %}
{% block description %}Agenda des concerts à venir d'Eloi Tembremande{% endblock %}

{% block body %}

{% load static %}
<section id="agenda" class="no-home">
  <nav id="main-nav">
    {% include "eloitembremande/partials/main-nav.html" %}
    <div class="image-bottom"><img src="{% static "img/agenda.jpg" %}"></div>
  </nav>
  <div class="page">
    <div class="soundwave"></div>
    <div class="container">
      <h1>Agenda</h1>
        {% for concert in object_list|dictsort:"date" %}
        {% ifchanged %}<h2>{{ concert.date.year }}</h2>{% endifchanged %}
        <div class="date">
          <div class="gauche">
            <div class="jour">{{ concert.date|date:'D d M' }}</div>
          </div>
          <div class="centre">
            <div class="projet">{{ concert.projet.nom }}</div>
            <div class="poste">{{ concert.projet.instruments }}</div>
          </div>
          <div class="droite">
            <div class="ville">{{ concert.ville }}</div>
            <div class="lieu">{{ concert.lieu }}</div>
          </div>
        </div>
        {% endfor %}
    </div>
  </div>
</section>

{% endblock %}

eloitembremande/templates/eloitembremande/pages/amis.html
{% extends "eloitembremande/base.html" %}
{% block description %}Les projets amis{% endblock %}

{% block body %}

{% load static %}
<section id="amis" class="no-home">
  <nav id="main-nav">
    {% include "eloitembremande/partials/main-nav.html" %}
  </nav>
  <div class="page">
    <div class="soundwave"></div>
    <div class="container">
      <h1>Amis</h1>
      <div class="projets">
        {% for projet in object_list %}
        {% if projet.ami %}
        <div class="projet">
          <h2>{{ projet.nom }}</h2>
          <div class="texte">
            <p>{{ projet.description|safe }}</p>
          </div>
          <div class="videos">
            {% for video in projet.video_set.all %}
              {{ video.code|safe }}
            {% endfor %}
          </div>
          <div class="contact">
            <div class="contact">
              <div class="phone">{{ projet.telephone|default_if_none:'' }}</div>
              <div class="mail">{{ projet.mail|default_if_none:'' }}</div>
              <div class="website"><a href="{{ projet.website }}" target="_blank">{{ projet.website|default_if_none:'' }}</a></div>
              <div class="socials">
                {% if projet.facebook %}<span class="facebook"><a href="{{ projet.facebook }}" target="_blank"><i class="fa fa-facebook-official"></i></a></span>{% endif %}
              </div>
            </div>
          </div>
        </div>
        {% endif %}
        {% endfor %}
      </div>
    </div>
  </div>
</section>

{% endblock %}

eloitembremande/templates/eloitembremande/pages/contact.html
{% extends "eloitembremande/base.html" %}
{% block description %}Contacts d'Eloi Tembremande et de ses projets{% endblock %}

{% block body %}

{% load static %}
<section id="contact" class="no-home">
  <nav id="main-nav" style="background-image: url({% static "img/contact.jpg" %});">
    {% include "eloitembremande/partials/main-nav.html" %}
  </nav>
  <div class="page">
    <div class="soundwave"></div>
    <div class="container">
      <h1>Éloi TEMBREMANDE</h1>
      <h2>eloi.tembremande@gmail.com</h2>
      <div class="contacts">
        {% for projet in object_list %}
        {% if not projet.ami %}
          <div class="contact">
            <h3>{{ projet.nom }}</h3>
            <div class="phone">{{ projet.telephone }}</div>
            <div class="mail">{{ projet.mail }}</div>
            <div class="website"><a href="{{ projet.website }}" target="_blank">{{ projet.website }}</a></div>
            <div class="socials">
              <span class="facebook"><a href="{{ projet.facebook }}" target="_blank"><i class="fa fa-facebook-official"></i></a></span>
            </div>
          </div>
        {% endif %}
        {% endfor %}
      </div>
    </div>
  </div>
</section>

{% endblock %}

eloitembremande/templates/eloitembremande/pages/home.html
{% extends "eloitembremande/base.html" %}

{% block body %}

  <section id="home">
    <nav id="home-nav">
      {% include "eloitembremande/partials/main-nav.html" %}
    </nav>
    <div class="page">
      <div class="photo"></div>
      <div class="title">
        <div class="soundwave"></div>
        <div class="citation">
          <div class="phrase">Les sensations sont les détails qui construisent l'histoire de notre vie.</div>
          <div class="signature">Oscar Wilde</div>
        </div>
        <h1>Éloi<br>Tembremande</h1>
      </div>
    </div>
  </section>

{% endblock %}

eloitembremande/templates/eloitembremande/pages/mentions-legales.html
{% extends "eloitembremande/base.html" %}
{% block description %}Mentions Légales du site web d'Eloi Tembremnde{% endblock %}

{% block body %}

{% load static %}
<section id="mentions-legales" class="no-home">
  <nav id="main-nav">
    {% include "eloitembremande/partials/main-nav.html" %}
  </nav>
  <div class="page">
    <div class="soundwave"></div>
    <div class="container">
      <h1>Mentions Légales</h1>

      <h2>Identification du site</h2>
      <p><b>Nom:</b> Eloi Tembremande<br>
      <b>URL:</b> eloitembremande.com</p>

      <h2>Propriétaire du site</h2>
      <p>Eloi Tembremande<br>
      Adresse<br>
      <b>Directeur de la publication:</b> Eloi Tembremande<br>
      <b>Directeur de la rédaction:</b> Eloi Tembremande</p>

      <h2>Hébergement</h2>
      <p>
        Association <b>Aquilenet</b><br>
        20 rue Tourat<br>
        33000 BORDEAUX<br>
        <a href="https://www.aquilenet.fr">www.aquilenet.fr</a>
      </p>

      <h2>Crédits</h2>
      <p>
        Site réalisé par Simon Crespeau<br>
        14 rue Riboutet 33670 CRÉON<br>
        Identification SIRET : 750 042 798 00025<br>
        <a href="https://www.art-e-toile.com">www.art-e-toile.com</a><br>
        <a href="mailto:simon@art-e-toile.com">simon@art-e-toile.com</a>
      </p>
      <p>
        WebDesign réalisé par Cerise Rousseau<br>
        Contacts
      </p>
      <p>
        Photos du site réalisées par Solweig Wood, Louise Rousseau et Manuel Ibanez<br>
        Tout droit réservé aux auteurs des photos.<br>
        Contacts
      </p>

      <h2>Politique sur le droit d'auteur</h2>
    </div>
  </div>
</section>

{% endblock %}

eloitembremande/templates/eloitembremande/pages/photos.html
{% extends "eloitembremande/base.html" %}
{% block description %}Galerie Photos d'Eloi Tembremande par Solweig Wood, Louise Rousseau et Manuel Ibanez{% endblock %}

{% block body %}

{% load static %}
<section id="photos" class="no-home">
  <nav id="main-nav">
    {% include "eloitembremande/partials/main-nav.html" %}
  </nav>
  <div class="page">
    <div class="soundwave"></div>
    <div class="container">
      <h1>Photos</h1>
      <div class="galerie">
        <div class="diaporama">
          <img src="{% static 'img/galeries/galerie1/01_thumb.jpg' %}" href="{% static 'img/galeries/galerie1/01.jpg' %}" alt="">
          <img src="{% static 'img/galeries/galerie1/02_thumb.jpg' %}" href="{% static 'img/galeries/galerie1/02.jpg' %}" alt="">
          <img src="{% static 'img/galeries/galerie1/03_thumb.jpg' %}" href="{% static 'img/galeries/galerie1/03.jpg' %}" alt="">
          <img src="{% static 'img/galeries/galerie1/04_thumb.jpg' %}" href="{% static 'img/galeries/galerie1/04.jpg' %}" alt="">
          <img src="{% static 'img/galeries/galerie1/05_thumb.jpg' %}" href="{% static 'img/galeries/galerie1/05.jpg' %}" alt="">
          <img src="{% static 'img/galeries/galerie1/06_thumb.jpg' %}" href="{% static 'img/galeries/galerie1/06.jpg' %}" alt="">
          <img src="{% static 'img/galeries/galerie1/07_thumb.jpg' %}" href="{% static 'img/galeries/galerie1/07.jpg' %}" alt="">
          <img src="{% static 'img/galeries/galerie1/08_thumb.jpg' %}" href="{% static 'img/galeries/galerie1/08.jpg' %}" alt="">
          <img src="{% static 'img/galeries/galerie1/09_thumb.jpg' %}" href="{% static 'img/galeries/galerie1/09.jpg' %}" alt="">
        </div>
      </div>

    </div>
  </div>
</section>

{% endblock %}

{% block scripts %}
<script type="text/javascript">
  $(document).ready(function() {
    $('.diaporama').each(function(){
      $(this).magnificPopup({
        delegate: 'img',
        type:'image',
        gallery: {
          enabled: true
        }
      });
    })
  });
</script>
{% endblock %}

eloitembremande/templates/eloitembremande/pages/projets.html
{% extends "eloitembremande/base.html" %}
{% block description %}Projets et groupes de musique d'Eloi Tembremande{% endblock %}

{% block body %}

{% load static %}
<section id="projets" class="no-home">
  <nav id="main-nav">
    {% include "eloitembremande/partials/main-nav.html" %}
    <div class="image-bottom"><img src="{% static 'img/projets.jpg' %}"></div>
  </nav>
  <div class="page">
    <div class="soundwave"></div>
    <div class="container">
      <h1>Projets</h1>
      {% for projet in object_list %}
      {% if not projet.ami %}
      <div class="projet">
        <h2>{{ projet.nom }}</h2>
        <div class="texte">
          {{ projet.description|safe }}
        </div>
        <div class="videos">
          {% for video in projet.video_set.all %}
            {{ video.code|safe }}
          {% endfor %}
        </div>
      </div>
      {% endif %}
      {% endfor %}
    </div>
  </div>
</section>

{% endblock %}

eloitembremande/templates/eloitembremande/partials/main-nav.html
<div class="hamburger">
  <i class="fa fa-bars"></i>
</div>
<ul class="links">
  <li><a href="{% url "home" %}">Accueil</a></li>
  <li><a href="{% url "projets" %}">Projets</a></li>
  <li><a href="{% url "agenda" %}">Agenda</a></li>
  <li><a href="{% url "photos" %}">Photos</a></li>
  <li><a href="{% url "amis" %}">Amis</a></li>
  <li><a href="{% url "contact" %}">Contact</a></li>
  <li class="plus"><a href="{% url "mentions-legales" %}">Mentions Légales</a></li>
</ul>